#include <iostream>
#include <vector>
#include <cmath>
#include <iomanip>
#include <cstdint>
using namespace std;

// --- 1. Dynamic Dimensions ---
const int SENSOR_PIXELS = 9; // A 3x3 grid flattened

// --- 2. The Hierarchical Neuron & Layer ---
struct LIF_Neuron {
    vector<int8_t> ternary_weights; 
    float membrane_potential = 0.0f; 
    uint64_t last_spike_time = 0;
};

struct CorticalLayer {
    string name;
    int layer_depth;
    vector<LIF_Neuron> clusters; // Dynamic width
    int expected_input_size;
    
    CorticalLayer(string n, int depth, int input_size) {
        name = n;
        layer_depth = depth;
        expected_input_size = input_size;
    }
};

// The Brain is now a dynamic stack of layers
vector<CorticalLayer> Brain;

// --- 3. The Hierarchical Forward Pass ---
// Returns the spikes generated by this layer to feed the next
vector<int8_t> process_layer(CorticalLayer& layer, const vector<int8_t>& incoming_signal) {
    vector<int8_t> outgoing_spikes;
    bool layer_spiked = false;

    // 1. Process existing clusters
    for (int c = 0; c < layer.clusters.size(); c++) {
        float raw_sum = 0.0f;
        int active_synapses = 0;
        
        // --- PATCHED: LOCALIZED RECEPTIVE FIELDS ---
        for (int i = 0; i < layer.expected_input_size; i++) {
            // Only evaluate pixels this specific neuron is physically wired to care about
            if (layer.clusters[c].ternary_weights[i] != 0) { 
                active_synapses++;
                
                // If the signal matches the expected feature, charge voltage
                if (incoming_signal[i] == layer.clusters[c].ternary_weights[i]) {
                    raw_sum += 1.0f;
                } 
                // If a feature it expects is missing, drain voltage
                else {
                    raw_sum -= 1.0f; 
                }
            }
        } // End of inner loop (i)

        if (active_synapses > 0) {
            float voltage = raw_sum / active_synapses;
            if (voltage > 0.75f) { // Hardcoded threshold for prototype clarity
                cout << "   -> [" << layer.name << "] Spike at Cluster " << c << " (Voltage: " << voltage << "mV)" << endl;
                outgoing_spikes.push_back(1);
                layer_spiked = true;
            } else {
                outgoing_spikes.push_back(0);
            }
        } else {
            outgoing_spikes.push_back(0);
        }
    } // End of outer loop (c)

    // 2. Spatial Neurogenesis (Expanding the Layer's Width)
    if (!layer_spiked) {
        // If the layer didn't recognize the input, grow a new cluster
        LIF_Neuron new_cluster;
        new_cluster.ternary_weights = incoming_signal; // Fast Hebbian wiring
        new_cluster.last_spike_time = 1;
        layer.clusters.push_back(new_cluster);
        
        cout << "   -> [" << layer.name << "] Anomaly. Width expanded. Formed Cluster " << layer.clusters.size() - 1 << endl;
        outgoing_spikes.push_back(1); // The new cluster immediately spikes
    }

    return outgoing_spikes;
}

// --- 4. The Global Brain Execution ---
void execute_cognitive_cycle(const vector<int8_t>& sensory_input, string object_name) {
    cout << "\n[Retina] Processing visual stimulus: " << object_name << endl;
    
    vector<int8_t> current_signal = sensory_input;

    for (int d = 0; d < Brain.size(); d++) {
        // Feed the signal into the current layer
        vector<int8_t> next_signal = process_layer(Brain[d], current_signal);
        
        // --- Z-AXIS NEUROGENESIS ---
        // If multiple clusters fire in the current layer, it means the object is a composite.
        // If we are at the top of the brain, we must grow a NEW layer to abstract it.
        int simultaneous_spikes = 0;
        for (int spike : next_signal) if (spike == 1) simultaneous_spikes++;

        if (simultaneous_spikes > 1 && d == Brain.size() - 1) {
            cout << "   [System] COMPOSITE OVERLOAD DETECTED IN " << Brain[d].name << "." << endl;
            cout << "   [System] Triggering Z-Axis Neurogenesis..." << endl;
            
            CorticalLayer new_layer("V" + to_string(d + 2) + " Cortex", d + 1, next_signal.size());
            Brain.push_back(new_layer);
            
            cout << "   [System] Brain deepened. Layer " << new_layer.name << " spawned." << endl;
        }
        
        // The output of this layer becomes the input of the next
        current_signal = next_signal; 
    }
}

int main() {
    cout << "=================================================" << endl;
    cout << " FP-SAN v6 | Dynamic Z-Axis Auto-Layering" << endl;
    cout << "=================================================\n" << endl;

    // Boot the brain with only a V1 Cortex (looks at 9 raw pixels)
    Brain.push_back(CorticalLayer("V1 Cortex", 0, SENSOR_PIXELS));

    // A 3x3 Grid
    vector<int8_t> horizontal_line = {1, 1, 1, 
                                      0, 0, 0, 
                                      0, 0, 0};
                                      
    vector<int8_t> vertical_line   = {0, 1, 0, 
                                      0, 1, 0, 
                                      0, 1, 0};
                                      
    vector<int8_t> cross_shape     = {1, 1, 1, 
                                      0, 1, 0, 
                                      0, 1, 0}; // Both horizontal and vertical combined

    cout << "--- PHASE 1: LEARNING BASIC EDGES ---" << endl;
    execute_cognitive_cycle(horizontal_line, "Horizontal Line");
    execute_cognitive_cycle(vertical_line, "Vertical Line");

    cout << "\n--- PHASE 2: ABSTRACTION & Z-AXIS SPAWNING ---" << endl;
    cout << "Feeding a 'Cross' shape. V1 will recognize both lines simultaneously." << endl;
    execute_cognitive_cycle(cross_shape, "The Cross Shape");

    cout << "\n--- PHASE 3: HIGHER ORDER RECALL ---" << endl;
    cout << "Feeding the 'Cross' again to ensure the new V2 layer abstracts it." << endl;
    execute_cognitive_cycle(cross_shape, "The Cross Shape (Again)");

    return 0;
}